# Generated by Django 5.1.3 on 2024-11-20 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.FloatField()),
                ('B', models.FloatField()),
                ('C', models.FloatField()),
                ('D', models.FloatField()),
                ('E', models.FloatField()),
                ('F', models.FloatField()),
                ('G', models.FloatField()),
                ('H', models.FloatField()),
                ('I', models.FloatField()),
                ('L', models.FloatField()),
                ('M', models.FloatField()),
                ('N', models.FloatField()),
                ('O', models.FloatField()),
                ('Q1', models.FloatField()),
                ('Q2', models.FloatField()),
                ('Q3', models.FloatField()),
                ('Q4', models.FloatField()),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('An', models.FloatField()),
                ('Ex', models.FloatField()),
                ('So', models.FloatField()),
                ('In', models.FloatField()),
                ('Ob', models.FloatField()),
                ('Cr', models.FloatField()),
                ('Ne', models.FloatField()),
                ('Ps', models.FloatField()),
                ('Li', models.FloatField()),
                ('Ac', models.FloatField()),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.respondent')),
            ],
        ),
    ]
