# Generated by Django 5.1.3 on 2024-11-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorization',
            name='Ac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='An',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='Cr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='Ex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='In',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='Li',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='Ne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='Ob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='Ps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='So',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='A',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='B',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='D',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='E',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='F',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='I',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='M',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='N',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='O',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='Q1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='Q2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='Q3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalityfactors',
            name='Q4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
