# Generated by Django 5.1.3 on 2024-11-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_categorization_ac_alter_categorization_an_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityfactors',
            name='D',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
