# Generated by Django 5.1.3 on 2024-11-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_personalityfactors_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalityfactors',
            name='D',
        ),
    ]
